apiVersion: apps/v1
kind: Deployment
metadata:
  name: population-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: population-api
  template:
    metadata:
      labels:
        app: population-api
    spec:
      containers:
        - name: population-api
          image: population-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: population-api-service
spec:
  type: NodePort
  selector:
    app: population-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
